package io.github.tieo.taghistory.apple.plist

import kotlin.io.encoding.Base64
import kotlin.io.encoding.ExperimentalEncodingApi
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertIs
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Fixtures are generated by CPython's `plistlib.dumps(..., FMT_BINARY)` —
 * the reference implementation Apple's SPD team also uses in tooling. Any
 * bplist00 that plistlib produces is legal for us to parse.
 */
@OptIn(ExperimentalEncodingApi::class)
class BinaryPlistTest {

    // dict with every primitive we parse: ASCII string, int, real, both bools,
    // bytes, nested array of ints, and an NSDate.
    private val fixturePrimitives = Base64.decode(
        "YnBsaXN0MDDYAQIDBAUGBwgJCgsMDQ4PE1RuYW1lVWNvdW50VXJhdGlvV2ZsYWdfb25YZmxhZ19vZmZU" +
            "YmxvYlVpdGVtc1R3aGVuVWhlbGxvECojP/gAAAAAAAAJCEQBAgMEoxAREhABEAIQAzNBxcj9YAAAAAgZ" +
            "HiQqMjtARktRU1xdXmNnaWttAAAAAAAAAQEAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAHY="
    )

    // Integers that overflow the 1-byte marker form: one large positive needing
    // 4 bytes, one negative needing the 8-byte signed form.
    private val fixtureInts = Base64.decode(
        "YnBsaXN0MDDSAQIDBFNiaWdTbmVnEwAAAAIYcRoAE///////////CA0RFR4AAAAAAAABAQAAAAAAAAAF" +
            "AAAAAAAAAAAAAAAAAAAAJw=="
    )

    // UTF-16BE string including a surrogate pair (🐶 = U+1F436).
    private val fixtureUnicode = Base64.decode(
        "YnBsaXN0MDDRAQJVZW1vamlqAGgA6QBsAGwAbwAgJgMAINg93DYICxEAAAAAAAABAQAAAAAAAAADAAAA" +
            "AAAAAAAAAAAAAAAAJg=="
    )

    // 20-entry dict forces the marker's low nibble to 0xF so the count spills
    // into a separate integer object. Covers the "extended count" code path.
    private val fixtureExtendedCount = Base64.decode(
        "YnBsaXN0MDDfEBQBAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fICEiIyQlJicoU2swMFNrMDFT" +
            "azAyU2swM1NrMDRTazA1U2swNlNrMDdTazA4U2swOVNrMTBTazExU2sxMlNrMTNTazE0U2sxNVNrMTZT" +
            "azE3U2sxOFNrMTkQABABEAIQAxAEEAUQBhAHEAgQCRAKEAsQDBANEA4QDxAQEBEQEhATCDM3Oz9DR0tP" +
            "U1dbX2Nna29zd3t/g4WHiYuNj5GTlZeZm52foaOlp6kAAAAAAAABAQAAAAAAAAApAAAAAAAAAAAAAAAA" +
            "AAAAqw=="
    )

    @Test
    fun detectsMagic() {
        assertTrue(BinaryPlist.isBinaryPlist(fixturePrimitives))
        assertTrue(BinaryPlist.isBinaryPlist("bplist00".encodeToByteArray()))
        assertTrue(!BinaryPlist.isBinaryPlist("<plist/>".encodeToByteArray()))
        assertTrue(!BinaryPlist.isBinaryPlist(ByteArray(4)))
    }

    @Test
    fun parsesPrimitives() {
        val dict = assertIs<PlistValue.Dict>(BinaryPlist.parse(fixturePrimitives))
        assertEquals("hello", dict.string("name"))
        assertEquals(42L, dict.int64("count"))
        assertEquals(1.5, (dict["ratio"] as PlistValue.Real).value)
        assertEquals(true, dict.bool("flag_on"))
        assertEquals(false, dict.bool("flag_off"))
        assertEquals(listOf<Byte>(1, 2, 3, 4), dict.data("blob")!!.toList())

        val items = assertNotNull(dict.array("items"))
        assertEquals(3, items.size)
        assertEquals(listOf(1L, 2L, 3L), items.items.map { (it as PlistValue.Int64).value })

        val when_ = assertIs<PlistValue.Date>(dict["when"])
        // plistlib stored a naive 2024-03-01T12:00:00 which we treat as UTC.
        assertEquals(1709294400000L, when_.epochMillis)
    }

    @Test
    fun parsesLargeAndNegativeInts() {
        val dict = assertIs<PlistValue.Dict>(BinaryPlist.parse(fixtureInts))
        assertEquals(9_000_000_000L, dict.int64("big"))
        // bplist00 stores -1 as the 8-byte two's-complement 0xFF..FF.
        assertEquals(-1L, dict.int64("neg"))
    }

    @Test
    fun parsesUnicodeWithSurrogatePair() {
        val dict = assertIs<PlistValue.Dict>(BinaryPlist.parse(fixtureUnicode))
        assertEquals("héllo ☃ 🐶", dict.string("emoji"))
    }

    @Test
    fun parsesExtendedCount() {
        val dict = assertIs<PlistValue.Dict>(BinaryPlist.parse(fixtureExtendedCount))
        assertEquals(20, dict.entries.size)
        for (i in 0 until 20) {
            val key = "k${i.toString().padStart(2, '0')}"
            assertEquals(i.toLong(), dict.int64(key), message = "entry $key")
        }
    }

    @Test
    fun rejectsNonBplistInput() {
        assertFailsWith<PlistParseException> {
            BinaryPlist.parse("<plist><dict/></plist>".encodeToByteArray())
        }
    }

    @Test
    fun rejectsTruncatedInput() {
        // Magic alone — no trailer.
        assertFailsWith<PlistParseException> {
            BinaryPlist.parse("bplist00".encodeToByteArray())
        }
    }
}
