package io.github.tieo.taghistory.apple.plist

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertIs

/**
 * End-to-end archiver-resolver tests using the same CKRecord fixture the
 * Java [NSKeyedArchiveReader] test exercises. Parity with the Java output
 * is the whole point — if the Kotlin port produced a different tree for
 * the same bytes, the migration would silently change behavior.
 */
class NSKeyedArchiveTest {

    // Three-entry CKRecord: RecordCtime (NSDate), RecordMtime (NSDate),
    // ModifiedByDevice (NSString). Generated by /tmp/gen_nskeyed_fixture.py
    // in the original Java test.
    private val ckRecordFixtureB64 =
        "YnBsaXN0MDDUAQIDBAUGKSxZJGFyY2hpdmVyWCRvYmplY3RzVCR0b3BYJHZlcnNpb25fEA9OU0tleWVk" +
            "QXJjaGl2ZXKqBwgVFhcYHB8gJlUkbnVsbNMJCgsMDRFWJGNsYXNzV05TLmtleXNaTlMub2JqZWN0c4AI" +
            "ow4PEIACgAOABKMSExSABYAGgAdbUmVjb3JkQ3RpbWVbUmVjb3JkTXRpbWVfEBBNb2RpZmllZEJ5RGV2" +
            "aWNl0gkZGhtXTlMudGltZYAJI0HFyP1gAAAA0gkZHR6ACSNBxcmwrAAAAFtteS1tYWMtMTIzNNIhIiMk" +
            "WCRjbGFzc2VzWiRjbGFzc25hbWWiJCVcTlNEaWN0aW9uYXJ5WE5TT2JqZWN00iEiJyiiKCVWTlNEYXRl" +
            "0SorVHJvb3SAARIAAYagAAgAEQAbACQAKQAyAEQATwBVAFwAYwBrAHYAeAB8AH4AgACCAIYAiACKAIwA" +
            "mACkALcAvADEAMYAzwDUANYA3wDrAPAA+QEEAQcBFAEdASIBJQEsAS8BNAE2AAAAAAAAAgEAAAAAAAAA" +
            "LQAAAAAAAAAAAAAAAAAAATs="

    @Test
    fun decodesCkRecordShape() {
        val tree = NSKeyedArchive.parseBase64(ckRecordFixtureB64)
        val dict = assertIs<PlistValue.Dict>(tree)

        val ctime = assertIs<PlistValue.Date>(dict["RecordCtime"])
        val mtime = assertIs<PlistValue.Date>(dict["RecordMtime"])
        assertEquals(isoMillis("2024-03-01T12:00:00Z"), ctime.epochMillis)
        assertEquals(isoMillis("2024-03-02T13:30:00Z"), mtime.epochMillis)

        assertEquals("my-mac-1234", dict.string("ModifiedByDevice"))
    }

    @Test
    fun rejectsNonArchiverPlist() {
        // A plain plist (not an NSKeyedArchiver blob) must fail loudly rather
        // than return a meaningless tree — the "is this actually an archive"
        // check is a safety rail against silently misinterpreting Apple
        // responses.
        val plainXml = XmlPlist.encode(plistDictOf("hello" to "world".asPlist()))
        val ex = assertFailsWith<PlistParseException> { NSKeyedArchive.parse(plainXml) }
        // The message mentions NSKeyedArchiver so future debugging is easy.
        kotlin.test.assertTrue(
            ex.message!!.contains("NSKeyedArchiver"),
            "Expected NSKeyedArchiver in message, got: ${ex.message}"
        )
    }

    // Turn "2024-03-01T12:00:00Z" into Unix epoch millis via XmlPlist's own
    // ISO 8601 parser, so the test doesn't duplicate the algorithm under test.
    private fun isoMillis(iso: String): Long {
        val xml = "<plist><date>$iso</date></plist>"
        return (XmlPlist.parse(xml) as PlistValue.Date).epochMillis
    }
}
