name: Generate APK (Release)
env:
  main_project_module: androidApp
  app_name: TagHistory
  KEYSTORE_FILE: release-keystore.jks
  ALIAS: upload

on:
  release:
    types: published

jobs:
  build:
    environment: 'Android Build Release'
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'release'
      && (github.event.release.prerelease == true || github.event.release.published_at != null)
      && startsWith(github.event.release.tag_name, 'android-app-v')

    steps:
      - name: Extract Version from Tag
        id: extract_version
        run: |
          FULL_TAG_NAME="${{ github.ref }}"
          TAG_WITHOUT_PREFIX="${FULL_TAG_NAME##refs/tags/}"
          START_INDEX=$(( $(echo "$TAG_WITHOUT_PREFIX" | awk -F'-v' '{print length($1)}') + 2 ))
          VERSION_STRING=$(echo "$TAG_WITHOUT_PREFIX" | cut -c "$START_INDEX"-)
          echo "Extracted version: $VERSION_STRING"
          echo "APP_VERSION=$VERSION_STRING" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Inject secrets.properties
        run: |
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > secrets.properties

      - name: Recreate release keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ${{ env.main_project_module }}/${{ env.KEYSTORE_FILE }}

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build Release APK
        run: |
          ./gradlew :androidApp:assembleRelease
          mv ${{ env.main_project_module }}/build/outputs/apk/release/androidApp-release.apk \
             ${{ env.main_project_module }}/build/outputs/apk/release/${{ env.app_name }}-${{ steps.extract_version.outputs.APP_VERSION }}.apk
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ env.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build Debug APK
        run: |
          ./gradlew :androidApp:assembleDebug
          mv ${{ env.main_project_module }}/build/outputs/apk/debug/androidApp-debug.apk \
             ${{ env.main_project_module }}/build/outputs/apk/debug/${{ env.app_name }}-${{ steps.extract_version.outputs.APP_VERSION }}-debug.apk
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ env.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK Debug artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.app_name }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.app_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload APK Release Asset to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: ${{ env.main_project_module }}/build/outputs/apk/release/${{ env.app_name }}-${{ steps.extract_version.outputs.APP_VERSION }}.apk
          name: ${{ env.app_name }} Android App ${{ steps.extract_version.outputs.APP_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_BUILD_RELEASE_GITHUB_TOKEN }}
